# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 685)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.msframe1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.msframe1.setObjectName("msframe1")
        self.horizontalLayout.addWidget(self.msframe1)
        self.msframe2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.msframe2.setObjectName("msframe2")
        self.horizontalLayout.addWidget(self.msframe2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.trace_layout = QtWidgets.QVBoxLayout()
        self.trace_layout.setObjectName("trace_layout")
        self.trace1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.trace1.setObjectName("trace1")
        self.trace_layout.addWidget(self.trace1)
        self.trace2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.trace2.setObjectName("trace2")
        self.trace_layout.addWidget(self.trace2)
        self.trace_layout.setStretch(0, 1)
        self.trace_layout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.trace_layout)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.celltable_layout = QtWidgets.QGridLayout()
        self.celltable_layout.setObjectName("celltable_layout")
        self.celltable_1 = QtWidgets.QTableWidget(self.centralwidget)
        self.celltable_1.setObjectName("celltable_1")
        self.celltable_1.setColumnCount(0)
        self.celltable_1.setRowCount(0)
        self.celltable_layout.addWidget(self.celltable_1, 0, 0, 1, 1)
        self.celltable_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.celltable_2.setObjectName("celltable_2")
        self.celltable_2.setColumnCount(0)
        self.celltable_2.setRowCount(0)
        self.celltable_layout.addWidget(self.celltable_2, 0, 1, 1, 1)
        self.cell1_label = QtWidgets.QLabel(self.centralwidget)
        self.cell1_label.setObjectName("cell1_label")
        self.celltable_layout.addWidget(self.cell1_label, 1, 0, 1, 1)
        self.cell2_label = QtWidgets.QLabel(self.centralwidget)
        self.cell2_label.setObjectName("cell2_label")
        self.celltable_layout.addWidget(self.cell2_label, 1, 1, 1, 1)
        self.goodcount_label = QtWidgets.QLabel(self.centralwidget)
        self.goodcount_label.setObjectName("goodcount_label")
        self.celltable_layout.addWidget(self.goodcount_label, 2, 0, 1, 1)
        self.badcount_label = QtWidgets.QLabel(self.centralwidget)
        self.badcount_label.setObjectName("badcount_label")
        self.celltable_layout.addWidget(self.badcount_label, 2, 1, 1, 1)
        self.celltable_layout.setColumnStretch(0, 1)
        self.celltable_layout.setColumnStretch(1, 1)
        self.celltable_layout.setRowStretch(0, 1)
        self.verticalLayout_2.addLayout(self.celltable_layout)
        self.control_layout = QtWidgets.QGridLayout()
        self.control_layout.setObjectName("control_layout")
        self.currentframe_label = QtWidgets.QLabel(self.centralwidget)
        self.currentframe_label.setObjectName("currentframe_label")
        self.control_layout.addWidget(self.currentframe_label, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.control_layout.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.sortmethod_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.sortmethod_comboBox.setObjectName("sortmethod_comboBox")
        self.control_layout.addWidget(self.sortmethod_comboBox, 0, 4, 1, 1)
        self.showgoodcell_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.showgoodcell_checkBox.setObjectName("showgoodcell_checkBox")
        self.control_layout.addWidget(self.showgoodcell_checkBox, 1, 0, 1, 2)
        self.zoom_label = QtWidgets.QLabel(self.centralwidget)
        self.zoom_label.setObjectName("zoom_label")
        self.control_layout.addWidget(self.zoom_label, 1, 2, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setMaximum(99)
        self.horizontalSlider_2.setSliderPosition(0)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.control_layout.addWidget(self.horizontalSlider_2, 1, 3, 1, 2)
        self.showbadcell_label = QtWidgets.QCheckBox(self.centralwidget)
        self.showbadcell_label.setObjectName("showbadcell_label")
        self.control_layout.addWidget(self.showbadcell_label, 2, 0, 1, 2)
        self.contour_label = QtWidgets.QLabel(self.centralwidget)
        self.contour_label.setObjectName("contour_label")
        self.control_layout.addWidget(self.contour_label, 2, 2, 1, 1)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.control_layout.addWidget(self.horizontalSlider_3, 2, 3, 1, 2)
        self.tracemode_label = QtWidgets.QLabel(self.centralwidget)
        self.tracemode_label.setObjectName("tracemode_label")
        self.control_layout.addWidget(self.tracemode_label, 3, 4, 1, 1)
        self.image1mode_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.image1mode_comboBox.setObjectName("image1mode_comboBox")
        self.control_layout.addWidget(self.image1mode_comboBox, 4, 0, 1, 2)
        self.image2mode_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.image2mode_comboBox.setObjectName("image2mode_comboBox")
        self.control_layout.addWidget(self.image2mode_comboBox, 4, 2, 1, 2)
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.control_layout.addWidget(self.comboBox_4, 4, 4, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.control_layout.addWidget(self.spinBox_2, 0, 1, 1, 2)
        self.image1_label = QtWidgets.QLabel(self.centralwidget)
        self.image1_label.setObjectName("image1_label")
        self.control_layout.addWidget(self.image1_label, 3, 0, 1, 2)
        self.image2_label = QtWidgets.QLabel(self.centralwidget)
        self.image2_label.setObjectName("image2_label")
        self.control_layout.addWidget(self.image2_label, 3, 2, 1, 2)
        self.control_layout.setColumnStretch(0, 1)
        self.control_layout.setColumnStretch(1, 1)
        self.control_layout.setColumnStretch(2, 1)
        self.control_layout.setColumnStretch(3, 1)
        self.control_layout.setColumnStretch(4, 1)
        self.control_layout.setRowStretch(0, 1)
        self.control_layout.setRowStretch(1, 1)
        self.control_layout.setRowStretch(2, 1)
        self.control_layout.setRowStretch(3, 1)
        self.control_layout.setRowStretch(4, 1)
        self.verticalLayout_2.addLayout(self.control_layout)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionAdd_Video = QtWidgets.QAction(MainWindow)
        self.actionAdd_Video.setObjectName("actionAdd_Video")
        self.actionImport_MS = QtWidgets.QAction(MainWindow)
        self.actionImport_MS.setObjectName("actionImport_MS")
        self.actionExport_MS = QtWidgets.QAction(MainWindow)
        self.actionExport_MS.setObjectName("actionExport_MS")
        self.actionExport_Binary_List = QtWidgets.QAction(MainWindow)
        self.actionExport_Binary_List.setObjectName("actionExport_Binary_List")
        self.actionSort_Cell = QtWidgets.QAction(MainWindow)
        self.actionSort_Cell.setObjectName("actionSort_Cell")
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionAdd_Video)
        self.menuFile.addAction(self.actionImport_MS)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_MS)
        self.menuFile.addAction(self.actionExport_Binary_List)
        self.menuAction.addAction(self.actionSort_Cell)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAction.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CellScreener"))
        self.cell1_label.setText(_translate("MainWindow", "Good"))
        self.cell2_label.setText(_translate("MainWindow", "Good"))
        self.goodcount_label.setText(_translate("MainWindow", "Good count"))
        self.badcount_label.setText(_translate("MainWindow", "Bad count"))
        self.currentframe_label.setText(_translate("MainWindow", "Current Frame"))
        self.pushButton_2.setText(_translate("MainWindow", "Sort cell by"))
        self.showgoodcell_checkBox.setText(_translate("MainWindow", "Show good cells"))
        self.zoom_label.setText(_translate("MainWindow", "Zoom"))
        self.showbadcell_label.setText(_translate("MainWindow", "Show bad cells"))
        self.contour_label.setText(_translate("MainWindow", "Contour"))
        self.tracemode_label.setText(_translate("MainWindow", "Trace"))
        self.image1_label.setText(_translate("MainWindow", "Image1"))
        self.image2_label.setText(_translate("MainWindow", "Image2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAction.setTitle(_translate("MainWindow", "Action"))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.actionAdd_Video.setText(_translate("MainWindow", "Add Video"))
        self.actionImport_MS.setText(_translate("MainWindow", "Import MS"))
        self.actionExport_MS.setText(_translate("MainWindow", "Export MS"))
        self.actionExport_Binary_List.setText(_translate("MainWindow", "Export Binary List"))
        self.actionSort_Cell.setText(_translate("MainWindow", "Sort Cell"))

